### ISSUE TITLE
v.net.model doesnt pop up in the QGIS toolbox

### ISSUE THREAD

**Issue by MotoMichelino** [benducke/v.net.models#42]
Dear Benjamin,
many thanks for all the effort that you put into the v.net.model (and congrats to the paper in JAMT)!
Unfortunately, with my set-up, the model doesnt pop up in the toolbox when opening QGIS.
I tried several versions of QGIS and GRASS 7 on two different machines with no results. 
Here I am using my laptop now (not super fast):

**Intel(R) Core(TM) i5 CPU       M 540  @ 2.53GHz   2.53 GHz
64-Bit-Betriebssystem, x64-basierter Prozessor**

with

**QGIS Desktop 3.10.12 with GRASS 7.8.4**

I downloaded and installed the MSYS.

the following documents have been copied:
![grafik](https://user-images.githubusercontent.com/121158586/208861425-77c83b58-e2b8-4734-a484-ea9e4574db2e.png)

and here:
![grafik](https://user-images.githubusercontent.com/121158586/208861615-46ebf52c-38c4-402a-b407-c157a6d87c7e.png)

and her again (I was not sure to copy the documents into "docs" or into "html" so I did both ..
![grafik](https://user-images.githubusercontent.com/121158586/208861817-8d55835c-2a44-4198-ab4b-0e308f4b1473.png)

here is the bat file:
![grafik](https://user-images.githubusercontent.com/121158586/208861997-498e83ce-dfba-4190-82b4-390109feb695.png)

and the scripts:
![grafik](https://user-images.githubusercontent.com/121158586/208862374-61af66e3-6fea-4f68-9153-f0a08fbc5fd6.png)

The same I did with the other versions and on the other machine in my office. My colleague simultaneously did it on his machine with Linux and it worked perfectly. So it probably is a windows-inherent thing or the machine itself (like department IT guy set-up)?
Most likely it is my ignorance that prevents the thing from working, though...
Maybe you have an idea?
Hope I provided all the info you need!

Many thanks for clarification and all the best,
Michael

**Comment by benducke** [comment]
Just to make sure: Did you install the files from the 1.0 release archive (https://github.com/benducke/v.net.models/releases)?
Or did you download the files directly from the repository (current development versions)?

**Comment by MotoMichelino** [comment]
Dear Benjamin,

das ists! Ich hatte die einzelnen Datein runtergeladen (ich meinte, 
ueber Dein paper da verwiesen worden zu sein).

Mit der zip v1.0 geht es!

Prima, tausend Dank!

werde es gleich ausprobieren und bin gespannt!

Beste Gruesse und frohes Neues Jahr

Michael

---
__
Dr. rer. nat. Michael Kempf (he/him)

CRC1266 -- Scales of Transformation
Project A2 'Integrative Modeling of Socio-Environmental Dynamics'

Christian-Albrechts-Universität zu Kiel
Department of Geography
Physical Geography -- Landscape Ecology and Geoinformation
Ludewig-Meyn-Str. 8 (R. 04.032)
24098 Kiel, Germany

Am 2022-12-25 14:16, schrieb Benjamin Ducke:

> Just to make sure: Did you install the files from the 1.0 release 
> archive (https://github.com/benducke/v.net.models/releases)?
> Or did you download the files directly from the repository (current 
> development versions)?
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>


Links:
------
[1] 
https://github.com/benducke/v.net.models/issues/42#issuecomment-1364680820
[2]

**Comment by MotoMichelino** [comment]
to add an english version to my previous answer:

works like a charm after downloading the v1.0 zip version from the link 
above!

Many thanks for clarification and all my best,

Michael

---
_

Am 2022-12-25 14:16, schrieb Benjamin Ducke:

> Just to make sure: Did you install the files from the 1.0 release 
> archive (https://github.com/benducke/v.net.models/releases)?
> Or did you download the files directly from the repository (current 
> development versions)?
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>


Links:
------
[1] 
https://github.com/benducke/v.net.models/issues/42#issuecomment-1364680820
[2]

**Comment by benducke** [comment]
Ok, good. I have added a corresponding note to Readme.md file.
